<?php
/**
 * $Id: xoops_version.php v 1.0 8 May 2004 hsalazar Exp $
 * Module: Wordbook - a multicategory glossary
 * Version: v 1.16
 * Release Date: 8 May 2004
 * Author: hsalazar
 * Additions: Dario Garcia
 * Licence: GNU
 */

$modversion['name'] = _MI_WB_MD_NAME;
$modversion['version'] = "1.17";
$modversion['description'] = _MI_WB_MD_DESC;
$modversion['author'] = "hsalazar";
$modversion['credits'] = "Catzwolf";
//$modversion['help'] = "help/wordbook.html";
$modversion["help"] = "about.php";
$modversion['official'] = 0;
$modversion['image'] = "images/wb_slogo.png";
$modversion['dirname'] = "wordbook";
// v.1.17
$modversion["license"] = "GNU see LICENSE";
$modversion["license_file"] = XOOPS_URL."/modules/wordbook/gpl.txt";
$modversion["release"] = "2006-11-30";

$modversion["author_website_url"] = "http://dev.xoops.org/modules/xfmod/project/?wordbook";
$modversion["author_website_name"] = "Wordbook on the Developers Forge";
$modversion["author_word"] = ":-)";
$modversion["module_status"] = "Release Candidate 1";

$modversion["module_team"] = "hsalazar, mondarse, alama";
$modversion["module_website_url"] = "http://dev.xoops.org/modules/xfmod/project/?wordbook";
$modversion["module_website_name"] = "Wordbook on the Developers Forge";

$modversion['demo_site_url'] = "http://www.somesite.net/modules/wordbook/";
$modversion['demo_site_name'] = "";
$modversion['submit_bug'] = "http://dev.xoops.org/modules/xfmod/tracker/?func=add&group_id=1019&atid=177";
$modversion['submit_feature'] = "http://dev.xoops.org/modules/xfmod/tracker/?func=add&group_id=1019&atid=180";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "wbcategories";
$modversion['tables'][1] = "wbentries";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "wb_search";

// Menu
global $xoopsUser, $xoopsDB, $xoopsModule;

$modversion['hasMain'] = 1;
$hModConfig =& xoops_gethandler('config');
$hModule =& xoops_gethandler('module');
if ($wordbookModule =& $hModule->getByDirname('wordbook'))
{
	$wordbookConfig =& $hModConfig->getConfigsByCat(0, $wordbookModule->getVar('mid'));
	//if ( isset($wordbookConfig['catsinmenu']) && $wordbookConfig['anonpost'] == 1 )
	if (($xoopsUser && ($wordbookConfig['allowsubmit'] == 1)) || ($wordbookConfig['anonpost'] == 1)) 
	{
	$modversion['sub'][1]['name'] = _MI_WB_SUB_SMNAME1;
	$modversion['sub'][1]['url'] = "submit.php";	
	}
}
//if ($xoopsUser)
//	{
//	$modversion['sub'][1]['name'] = _MI_WB_SUB_SMNAME1;
//	$modversion['sub'][1]['url'] = "submit.php";
//	}
$modversion['sub'][2]['name'] = _MI_WB_SUB_SMNAME2;
$modversion['sub'][2]['url'] = "request.php";
$modversion['sub'][3]['name'] = _MI_WB_SUB_SMNAME3;
$modversion['sub'][3]['url'] = "search.php";


$sql = $xoopsDB->query( "SELECT categoryID, name FROM " . $xoopsDB->prefix( "wbcategories" ) . " " );
$i = 3;
$hModConfig =& xoops_gethandler('config');
$hModule =& xoops_gethandler('module');
if ($wordbookModule =& $hModule->getByDirname('wordbook'))
{
	$wordbookConfig =& $hModConfig->getConfigsByCat(0, $wordbookModule->getVar('mid'));
	if ( isset($wordbookConfig['catsinmenu']) && $wordbookConfig['catsinmenu'] == 1 )
	{
	while ( list( $categoryID, $name ) = $xoopsDB->fetchRow( $sql ) )
		{
		$modversion['sub'][$i]['name'] = $name;
		$modversion['sub'][$i]['url'] = "category.php?categoryID=" . $categoryID . "";
		$i++;
		} 
	}
}
// blocks
$modversion['blocks'][1]['file'] = "entries_new.php";
$modversion['blocks'][1]['name'] = _MI_WB_ENTRIESNEW;
$modversion['blocks'][1]['description'] = "Shows new entries";
$modversion['blocks'][1]['show_func'] = "b_entries_new_show";
$modversion['blocks'][1]['edit_func'] = "b_entries_new_edit";
$modversion['blocks'][1]['options'] = "datesub|5";
$modversion['blocks'][1]['template'] = "entries_new.html";

$modversion['blocks'][2]['file'] = "entries_top.php";
$modversion['blocks'][2]['name'] = _MI_WB_ENTRIESTOP;
$modversion['blocks'][2]['description'] = "Shows popular entries";
$modversion['blocks'][2]['show_func'] = "b_entries_top_show";
$modversion['blocks'][2]['edit_func'] = "b_entries_top_edit";
$modversion['blocks'][2]['options'] = "counter|5";
$modversion['blocks'][2]['template'] = "entries_top.html";

$modversion['blocks'][3]['file'] = "random_term.php";
$modversion['blocks'][3]['name'] = _MI_WB_RANDOMTERM;
$modversion['blocks'][3]['description'] = "Shows a random term";
$modversion['blocks'][3]['show_func'] = "b_entries_random_show";
$modversion['blocks'][3]['template'] = "entries_random.html";

// Templates
$modversion['templates'][1]['file'] = 'wb_category.html';
$modversion['templates'][1]['description'] = 'Display categories';
$modversion['templates'][2]['file'] = 'wb_index.html';
$modversion['templates'][2]['description'] = 'Display index';
$modversion['templates'][3]['file'] = 'wb_entry.html';
$modversion['templates'][3]['description'] = 'Display entry';
$modversion['templates'][4]['file'] = 'wb_letter.html';
$modversion['templates'][4]['description'] = 'Display letter';
$modversion['templates'][5]['file'] = 'wb_search.html';
$modversion['templates'][5]['description'] = 'Search in glossary';
$modversion['templates'][6]['file'] = 'wb_request.html';
$modversion['templates'][6]['description'] = 'Request a definition';
$modversion['templates'][7]['file'] = 'wb_submit.html';
$modversion['templates'][7]['description'] = 'Submit a definition';
// 1.17
$modversion['templates'][8]['file'] = "wb_adminmenu.html";
$modversion['templates'][8]['description'] = '(Admin) Tabs bar for administration pages';


// Config Settings (only for modules that need config settings generated automatically)
$cf=1;
$modversion['config'][$cf] = array(
	'name' => 'allowsubmit',
	'title'  => '_MI_WB_ALLOWSUBMIT',
	'description' => '_MI_WB_ALLOWSUBMITDSC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 1);

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'anonpost',
	'title' => '_MI_WB_ANONSUBMIT',
	'description' => '_MI_WB_ANONSUBMITDSC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 0);

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'dateformat',
	'title' => '_MI_WB_DATEFORMAT',
	'description' => '_MI_WB_DATEFORMATDSC',
	'formtype' => 'textbox',
	'valuetype' => 'text',
	'default' => 'd-M-Y H:i');

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'perpage',
	'title' => '_MI_WB_PERPAGE',
	'description' => '_MI_WB_PERPAGEDSC',
	'formtype' => 'select',
	'valuetype' => 'int',
	'default' => 10,
	'options' => array( '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 ));

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'indexperpage',
	'title' => '_MI_WB_PERPAGEINDEX',
	'description' => '_MI_WB_PERPAGEINDEXDSC',
	'formtype' => 'select',
	'valuetype' => 'int',
	'default' => 10,
	'options' => array( '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 ));

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'autoapprove',
	'title' => '_MI_WB_AUTOAPPROVE',
	'description' => '_MI_WB_AUTOAPPROVEDSC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 0);

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'multicats',
	'title' => '_MI_WB_MULTICATS',
	'description' => '_MI_WB_MULTICATSDSC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 1);

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'catsinmenu',
	'title' => '_MI_WB_CATSINMENU',
	'description' => '_MI_WB_CATSINMENUDSC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 0);

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'catsperindex',
	'title' => '_MI_WB_CATSPERINDEX',
	'description' => '_MI_WB_CATSPERINDEXDSC',
	'formtype' => 'select',
	'valuetype' => 'int',
	'default' => 3,
	'options' => array( '1' => 1, '3' => 3, '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 ));

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'adminhits',
	'title' => '_MI_WB_ALLOWADMINHITS',
	'description' => '_MI_WB_ALLOWADMINHITSDSC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 0);

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'mailtoadmin',
	'title' => '_MI_WB_MAILTOADMIN',
	'description' => '_MI_WB_MAILTOADMINDSC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 1);

$cf++;
$modversion['config'][$cf] = array(
	'name' => 'rndlength',
	'title' => '_MI_WB_RANDOMLENGTH',
	'description' => '_MI_WB_RANDOMLENGTHDSC',
	'formtype' => 'textbox',
	'valuetype' => 'int',
	'default' => 150);

$cf++; //13
$modversion['config'][$cf] = array(
	'name' => 'linkterms',
	'title' => '_MI_WB_LINKTERMS',
	'description' => '_MI_WB_LINKTERMSDSC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 1);

//Comments (Mondarse)
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'entryID';
$modversion['comments']['pageName'] = 'entry.php';

$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'wordbook_com_approve';
$modversion['comments']['callback']['update'] = 'wordbook_com_update';
//Comments (Mondarse)

// On Update
if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok' && $_POST['dirname'] == $modversion['dirname'] ) {
	include dirname( __FILE__ ) . "/include/onupdate.inc.php" ;
}
?>
